from fastapi import APIRouter, Depends, status
from sqlalchemy.orm import Session
from app.database import get_db
from app.schemas.wazuh import WazuhAlertPayload
from app.services.wazuh_collector import wazuh_collector

router = APIRouter(prefix="/wazuh", tags=["Wazuh SIEM Integration"])

@router.post("/webhook", status_code=status.HTTP_201_CREATED)
async def receive_wazuh_alert(
    payload: WazuhAlertPayload,
    db: Session = Depends(get_db)
):
    """
    Receives real-time Wazuh SIEM JSON alert webhooks generated by Logstash / Wazuh Manager,
    runs LLM threat triage, and executes automated firewall isolation.
    """
    result = await wazuh_collector.process_wazuh_webhook(db, payload)
    return result

@router.get("/status")
def get_wazuh_status():
    return {
        "status": "ONLINE",
        "wazuh_webhook_endpoint": "/api/v1/wazuh/webhook",
        "supported_rules": ["5712 (SSHD Brute Force)", "31101 (SQL Injection)", "5710 (SSH Invalid User)"]
    }
